// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package srvmocks is a generated GoMock package.
package srvmocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Quasar777/courier-service/internal/handler/dto"
	model "github.com/Quasar777/courier-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCourierUseCase is a mock of CourierUseCase interface.
type MockCourierUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCourierUseCaseMockRecorder
}

// MockCourierUseCaseMockRecorder is the mock recorder for MockCourierUseCase.
type MockCourierUseCaseMockRecorder struct {
	mock *MockCourierUseCase
}

// NewMockCourierUseCase creates a new mock instance.
func NewMockCourierUseCase(ctrl *gomock.Controller) *MockCourierUseCase {
	mock := &MockCourierUseCase{ctrl: ctrl}
	mock.recorder = &MockCourierUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierUseCase) EXPECT() *MockCourierUseCaseMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockCourierUseCase) CreateCourier(ctx context.Context, req dto.CreateCourierRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockCourierUseCaseMockRecorder) CreateCourier(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockCourierUseCase)(nil).CreateCourier), ctx, req)
}

// DeleteCourier mocks base method.
func (m *MockCourierUseCase) DeleteCourier(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCourier", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCourier indicates an expected call of DeleteCourier.
func (mr *MockCourierUseCaseMockRecorder) DeleteCourier(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCourier", reflect.TypeOf((*MockCourierUseCase)(nil).DeleteCourier), ctx, id)
}

// GetCourier mocks base method.
func (m *MockCourierUseCase) GetCourier(ctx context.Context, id int) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourier", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourier indicates an expected call of GetCourier.
func (mr *MockCourierUseCaseMockRecorder) GetCourier(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourier", reflect.TypeOf((*MockCourierUseCase)(nil).GetCourier), ctx, id)
}

// GetCouriers mocks base method.
func (m *MockCourierUseCase) GetCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCouriers indicates an expected call of GetCouriers.
func (mr *MockCourierUseCaseMockRecorder) GetCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouriers", reflect.TypeOf((*MockCourierUseCase)(nil).GetCouriers), ctx)
}

// UpdateCourier mocks base method.
func (m *MockCourierUseCase) UpdateCourier(ctx context.Context, req dto.UpdateCourierRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockCourierUseCaseMockRecorder) UpdateCourier(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockCourierUseCase)(nil).UpdateCourier), ctx, req)
}

// MockDeliveryUseCase is a mock of DeliveryUseCase interface.
type MockDeliveryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryUseCaseMockRecorder
}

// MockDeliveryUseCaseMockRecorder is the mock recorder for MockDeliveryUseCase.
type MockDeliveryUseCaseMockRecorder struct {
	mock *MockDeliveryUseCase
}

// NewMockDeliveryUseCase creates a new mock instance.
func NewMockDeliveryUseCase(ctrl *gomock.Controller) *MockDeliveryUseCase {
	mock := &MockDeliveryUseCase{ctrl: ctrl}
	mock.recorder = &MockDeliveryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryUseCase) EXPECT() *MockDeliveryUseCaseMockRecorder {
	return m.recorder
}

// AssignCourier mocks base method.
func (m *MockDeliveryUseCase) AssignCourier(ctx context.Context, req dto.AssignDeliveryRequest) (*dto.AssignedDeliveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourier", ctx, req)
	ret0, _ := ret[0].(*dto.AssignedDeliveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourier indicates an expected call of AssignCourier.
func (mr *MockDeliveryUseCaseMockRecorder) AssignCourier(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourier", reflect.TypeOf((*MockDeliveryUseCase)(nil).AssignCourier), ctx, req)
}

// UnassignCourier mocks base method.
func (m *MockDeliveryUseCase) UnassignCourier(ctx context.Context, req dto.UnassignDeliveryRequest) (*dto.UnassignedDeliveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignCourier", ctx, req)
	ret0, _ := ret[0].(*dto.UnassignedDeliveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignCourier indicates an expected call of UnassignCourier.
func (mr *MockDeliveryUseCaseMockRecorder) UnassignCourier(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignCourier", reflect.TypeOf((*MockDeliveryUseCase)(nil).UnassignCourier), ctx, req)
}
