version: '3'

services:
  postgres_test:
    image: postgres:15
    container_name: courier-service-postgres-test
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: ${POSTGRES_USER}          # Имя пользователя БД (берем из .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Пароль (берем из .env)
      POSTGRES_DB: ${POSTGRES_DB}              # База данных, создаваемая при запуске (берем из .env)
    volumes:
      - pgdata_test:/var/lib/postgresql/data   # Хранилище данных
    ports:
      - "${POSTGRES_PORT}:5432"                # Проброс порта: хост:контейнер (хост берем из .env)

volumes:
  pgdata_test:


# Команда для запуска тестового контейнера: docker compose -f docker-compose.test.yml up -d