// Code generated by MockGen. DO NOT EDIT.
// Source: delivery/contract.go

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/Quasar777/courier-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// GetCourierIdWithFewestOrders mocks base method.
func (m *MockCourierRepository) GetCourierIdWithFewestOrders(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierIdWithFewestOrders", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierIdWithFewestOrders indicates an expected call of GetCourierIdWithFewestOrders.
func (mr *MockCourierRepositoryMockRecorder) GetCourierIdWithFewestOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierIdWithFewestOrders", reflect.TypeOf((*MockCourierRepository)(nil).GetCourierIdWithFewestOrders), ctx)
}

// GetOneById mocks base method.
func (m *MockCourierRepository) GetOneById(ctx context.Context, id int) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneById", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneById indicates an expected call of GetOneById.
func (mr *MockCourierRepositoryMockRecorder) GetOneById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneById", reflect.TypeOf((*MockCourierRepository)(nil).GetOneById), ctx, id)
}

// ReleaseCouriers mocks base method.
func (m *MockCourierRepository) ReleaseCouriers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCouriers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseCouriers indicates an expected call of ReleaseCouriers.
func (mr *MockCourierRepositoryMockRecorder) ReleaseCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCouriers", reflect.TypeOf((*MockCourierRepository)(nil).ReleaseCouriers), ctx)
}

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// AssignCourierWithUpdate mocks base method.
func (m *MockDeliveryRepository) AssignCourierWithUpdate(ctx context.Context, courierId int, orderId string, deadline time.Time) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourierWithUpdate", ctx, courierId, orderId, deadline)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourierWithUpdate indicates an expected call of AssignCourierWithUpdate.
func (mr *MockDeliveryRepositoryMockRecorder) AssignCourierWithUpdate(ctx, courierId, orderId, deadline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourierWithUpdate", reflect.TypeOf((*MockDeliveryRepository)(nil).AssignCourierWithUpdate), ctx, courierId, orderId, deadline)
}

// UnassignWithUpdate mocks base method.
func (m *MockDeliveryRepository) UnassignWithUpdate(ctx context.Context, orderId string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignWithUpdate", ctx, orderId)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignWithUpdate indicates an expected call of UnassignWithUpdate.
func (mr *MockDeliveryRepositoryMockRecorder) UnassignWithUpdate(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignWithUpdate", reflect.TypeOf((*MockDeliveryRepository)(nil).UnassignWithUpdate), ctx, orderId)
}

// MockDeadlineCalculator is a mock of DeadlineCalculator interface.
type MockDeadlineCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockDeadlineCalculatorMockRecorder
}

// MockDeadlineCalculatorMockRecorder is the mock recorder for MockDeadlineCalculator.
type MockDeadlineCalculatorMockRecorder struct {
	mock *MockDeadlineCalculator
}

// NewMockDeadlineCalculator creates a new mock instance.
func NewMockDeadlineCalculator(ctrl *gomock.Controller) *MockDeadlineCalculator {
	mock := &MockDeadlineCalculator{ctrl: ctrl}
	mock.recorder = &MockDeadlineCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeadlineCalculator) EXPECT() *MockDeadlineCalculatorMockRecorder {
	return m.recorder
}

// CalculateDeadline mocks base method.
func (m *MockDeadlineCalculator) CalculateDeadline() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDeadline")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CalculateDeadline indicates an expected call of CalculateDeadline.
func (mr *MockDeadlineCalculatorMockRecorder) CalculateDeadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDeadline", reflect.TypeOf((*MockDeadlineCalculator)(nil).CalculateDeadline))
}

// MockdeadlineCalculatorFactory is a mock of deadlineCalculatorFactory interface.
type MockdeadlineCalculatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockdeadlineCalculatorFactoryMockRecorder
}

// MockdeadlineCalculatorFactoryMockRecorder is the mock recorder for MockdeadlineCalculatorFactory.
type MockdeadlineCalculatorFactoryMockRecorder struct {
	mock *MockdeadlineCalculatorFactory
}

// NewMockdeadlineCalculatorFactory creates a new mock instance.
func NewMockdeadlineCalculatorFactory(ctrl *gomock.Controller) *MockdeadlineCalculatorFactory {
	mock := &MockdeadlineCalculatorFactory{ctrl: ctrl}
	mock.recorder = &MockdeadlineCalculatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeadlineCalculatorFactory) EXPECT() *MockdeadlineCalculatorFactoryMockRecorder {
	return m.recorder
}

// GetDeliveryCalculator mocks base method.
func (m *MockdeadlineCalculatorFactory) GetDeliveryCalculator(courierType model.CourierTransportType) DeadlineCalculator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryCalculator", courierType)
	ret0, _ := ret[0].(DeadlineCalculator)
	return ret0
}

// GetDeliveryCalculator indicates an expected call of GetDeliveryCalculator.
func (mr *MockdeadlineCalculatorFactoryMockRecorder) GetDeliveryCalculator(courierType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryCalculator", reflect.TypeOf((*MockdeadlineCalculatorFactory)(nil).GetDeliveryCalculator), courierType)
}
