// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mock_usecase is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/Quasar777/courier-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourierRepository) Create(ctx context.Context, courier *model.CreateCourierRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, courier)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCourierRepositoryMockRecorder) Create(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourierRepository)(nil).Create), ctx, courier)
}

// Delete mocks base method.
func (m *MockCourierRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCourierRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCourierRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockCourierRepository) GetAll(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCourierRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCourierRepository)(nil).GetAll), ctx)
}

// GetOneById mocks base method.
func (m *MockCourierRepository) GetOneById(ctx context.Context, id int) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneById", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneById indicates an expected call of GetOneById.
func (mr *MockCourierRepositoryMockRecorder) GetOneById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneById", reflect.TypeOf((*MockCourierRepository)(nil).GetOneById), ctx, id)
}

// ReleaseCouriers mocks base method.
func (m *MockCourierRepository) ReleaseCouriers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCouriers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseCouriers indicates an expected call of ReleaseCouriers.
func (mr *MockCourierRepositoryMockRecorder) ReleaseCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCouriers", reflect.TypeOf((*MockCourierRepository)(nil).ReleaseCouriers), ctx)
}

// Update mocks base method.
func (m *MockCourierRepository) Update(ctx context.Context, courier *model.UpdateCourierRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourierRepositoryMockRecorder) Update(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourierRepository)(nil).Update), ctx, courier)
}

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// AssignCourierWithUpdate mocks base method.
func (m *MockDeliveryRepository) AssignCourierWithUpdate(ctx context.Context, courierId int, orderId string, deadline time.Time) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCourierWithUpdate", ctx, courierId, orderId, deadline)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignCourierWithUpdate indicates an expected call of AssignCourierWithUpdate.
func (mr *MockDeliveryRepositoryMockRecorder) AssignCourierWithUpdate(ctx, courierId, orderId, deadline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCourierWithUpdate", reflect.TypeOf((*MockDeliveryRepository)(nil).AssignCourierWithUpdate), ctx, courierId, orderId, deadline)
}

// GetCourierIdWithFewestOrders mocks base method.
func (m *MockDeliveryRepository) GetCourierIdWithFewestOrders(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourierIdWithFewestOrders", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourierIdWithFewestOrders indicates an expected call of GetCourierIdWithFewestOrders.
func (mr *MockDeliveryRepositoryMockRecorder) GetCourierIdWithFewestOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourierIdWithFewestOrders", reflect.TypeOf((*MockDeliveryRepository)(nil).GetCourierIdWithFewestOrders), ctx)
}

// UnassignWithUpdate mocks base method.
func (m *MockDeliveryRepository) UnassignWithUpdate(ctx context.Context, orderId string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignWithUpdate", ctx, orderId)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignWithUpdate indicates an expected call of UnassignWithUpdate.
func (mr *MockDeliveryRepositoryMockRecorder) UnassignWithUpdate(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignWithUpdate", reflect.TypeOf((*MockDeliveryRepository)(nil).UnassignWithUpdate), ctx, orderId)
}

// MockIDeadlineFactory is a mock of IDeadlineFactory interface.
type MockIDeadlineFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIDeadlineFactoryMockRecorder
}

// MockIDeadlineFactoryMockRecorder is the mock recorder for MockIDeadlineFactory.
type MockIDeadlineFactoryMockRecorder struct {
	mock *MockIDeadlineFactory
}

// NewMockIDeadlineFactory creates a new mock instance.
func NewMockIDeadlineFactory(ctrl *gomock.Controller) *MockIDeadlineFactory {
	mock := &MockIDeadlineFactory{ctrl: ctrl}
	mock.recorder = &MockIDeadlineFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeadlineFactory) EXPECT() *MockIDeadlineFactoryMockRecorder {
	return m.recorder
}

// Deadline mocks base method.
func (m *MockIDeadlineFactory) Deadline(now time.Time, transportType string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline", now, transportType)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Deadline indicates an expected call of Deadline.
func (mr *MockIDeadlineFactoryMockRecorder) Deadline(now, transportType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockIDeadlineFactory)(nil).Deadline), now, transportType)
}
